name: Publish to gh-pages

on:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
    merge-main:
        runs-on: ubuntu-latest
        steps:
            - run: git checkout gh-pages
            - run: git merge main
            - run: git push origin gh-pages
